apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  url: cG9zdGdyZXNxbDovL2RvYWRtaW46QVZOU19sM29wMGFfeE1oT2hzdVpVVG5tQG5sdy11bml0ZS1k
by11c2VyLTE2MjM4MDkwLTAuYy5kYi5vbmRpZ2l0YWxvY2Vhbi5jb206MjUwNjAvbmx3LXVuaXRl
P3NzbG1vZGU9cmVxdWlyZQo=
